//! __NAME__ — a rustango-cms site (generated by `rcms new`).
//!
//! Bootstrap, then run:
//!
//! ```sh
//! createdb __NAME__
//! export DATABASE_URL=postgres://localhost/__NAME__
//! cargo run -- init-tenancy
//! cargo run -- create-tenant demo
//! cargo run -- migrate-tenants
//! cargo run -- runserver
//! # admin: http://demo.localtest.me:8080/cms-admin/pages
//! ```
//!
//! SQLite (no DB server): build with `--no-default-features --features sqlite`
//! and create the tenant in database-mode (`--mode database --host-pattern …`)
//! — see the README for the exact commands.

mod models;

use std::path::Path;
use std::sync::Arc;

use tera::Tera;

#[rustango::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Force-link the page-type registrations into the binary's inventory.
    // Without these references the optimizer may drop the static-init
    // blocks that submit the handlers. Add one line per page type.
    let _ = std::any::type_name::<models::HomePage>();
    let _ = std::any::type_name::<models::ArticlePage>();

    // Public templates live in ./templates; the bundled admin templates
    // are registered on top by `register_templates`.
    let templates_glob = format!("{}/templates/**/*.html", env!("CARGO_MANIFEST_DIR"));
    let mut tera = Tera::new(&templates_glob)?;
    rustango_cms::admin::register_templates(&mut tera)?;
    // Public-render helpers used by site templates: markdown / rich text, the
    // `t` content-translation filter, StreamField block rendering, menus,
    // child listings, page URLs, snippets, image renditions, and locale-aware
    // dates. Registered up front so starter templates (and ones you add) work
    // without tracking down "filter/function not found" errors.
    rustango_cms::markdown::register_tera_filter(&mut tera);
    rustango_cms::richtext::register_tera_filter(&mut tera);
    rustango_cms::translation::register_tera_filter(&mut tera);
    rustango_cms::block::tera_helpers::register_tera_function(&mut tera);
    rustango_cms::auto_menu::register_tera_function(&mut tera);
    rustango_cms::children_filtered::register_tera_function(&mut tera);
    rustango_cms::page_url::register_tera_function(&mut tera);
    rustango_cms::snippet_render::register_tera_function(&mut tera);
    rustango_cms::rendition::register_tera_function(&mut tera);
    rustango_cms::date_filters::register_tera_filters(&mut tera);
    let tera = Arc::new(tera);

    let migrations_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("migrations");
    // Backfill any CMS migrations newer than the ones written at generation
    // time, so this app always has the current schema regardless of when it
    // was scaffolded. Skips files that already exist; safe to run every boot.
    rustango_cms::migrations::materialize(&migrations_dir)?;

    // Admin routing has two halves that must BOTH be mounted:
    //   • `public_router` — pre-auth routes: the branded `/login`, password
    //     reset, and the admin static assets (cms.css + JS). Without it the
    //     admin CSS/JS 404 (the public renderer's fallback claims them) and
    //     the admin renders unstyled.
    //   • `with_login_required(router(…))` — the login-gated `/cms-admin/*`
    //     CRUD (anonymous visitors 302 to `/login?next=…`).
    // Then merge the public CMS renderer, which claims the site root.
    let cms_admin = rustango_cms::admin::public_router(tera.clone()).merge(
        rustango_cms::admin::with_login_required(
            rustango_cms::admin::router(tera.clone()),
            "/login",
        ),
    );
    let api = cms_admin.merge(rustango_cms::router(tera));

    // The bundled admin forms emit `{{ csrf_token | csrf_input | safe }}`;
    // wire the matching CSRF middleware so tokens are validated on submit.
    // Drop `allow_insecure_for_dev()` in production (HTTPS) to re-enable
    // the cookie's `Secure` attribute.
    //
    // `exempt_prefix` is required, not optional: the analytics beacon that
    // every public page injects POSTs to `/__cms__/collect` via
    // `navigator.sendBeacon`, which can't attach an `X-CSRF-Token` — and a
    // CDN-cached page may never have received a CSRF cookie at all. Without
    // the exemption every beacon 403s and the analytics dashboard stays empty
    // with no visible error.
    let csrf_cfg = rustango::forms::csrf::CsrfConfig::default()
        .exempt_prefix(rustango_cms::analytics::COLLECT_PATH)
        .allow_insecure_for_dev();

    rustango::manage::Cli::new()
        .tenancy()
        .api(api)
        .migrations_dir(migrations_dir)
        .with_csrf_config(csrf_cfg)
        .seed(|registry| {
            let pool = registry.clone();
            async move {
                rustango_cms::ensure_seeded(&pool).await?;
                // Publish scheduled pages and take expired ones down on
                // time. Pass your page-cache invalidator here if you add one.
                rustango_cms::spawn_schedule_sweeper(
                    &pool,
                    std::time::Duration::from_secs(60),
                    rustango_cms::cache_invalidate::noop(),
                );
                Ok(())
            }
        })
        .run()
        .await
}
