//! __NAME__ — a rustango-cms site (generated by `rcms new`).
//!
//! How to set up the database and run it — SQLite or PostgreSQL — is in
//! the README.
//!
//! In production, set `RUSTANGO_ENV=prod` (secure cookies) and, when the
//! binary runs away from this folder, `RCMS_SITE_DIR` to the folder that
//! holds `templates/` and `migrations/`.

mod models;

use std::path::PathBuf;
use std::sync::Arc;

use tera::Tera;

/// The folder holding `templates/` and `migrations/`: `RCMS_SITE_DIR` when
/// set — a release binary deployed away from its source — else this
/// project's folder.
fn site_dir() -> PathBuf {
    std::env::var_os("RCMS_SITE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(env!("CARGO_MANIFEST_DIR")))
}

/// `RUSTANGO_ENV=prod` (or `production`): the framework's switch for secure
/// session cookies, used here for the CSRF cookie too.
fn is_production() -> bool {
    matches!(std::env::var("RUSTANGO_ENV").as_deref(), Ok("prod" | "production"))
}

#[rustango::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Force-link the page-type registrations into the binary's inventory.
    // Without these references the optimizer may drop the static-init
    // blocks that submit the handlers. Add one line per page type.
    let _ = std::any::type_name::<models::HomePage>();
    let _ = std::any::type_name::<models::ArticlePage>();

    // Public templates live in ./templates; the bundled admin templates
    // are registered on top by `register_templates`.
    let templates_glob = format!("{}/templates/**/*.html", site_dir().display());
    let mut tera = Tera::new(&templates_glob)?;
    rustango_cms::admin::register_templates(&mut tera)?;
    // Public-render helpers used by site templates: markdown / rich text, the
    // `t` content-translation filter, StreamField block rendering, menus,
    // child listings, page URLs, snippets, image renditions, and locale-aware
    // dates. Registered up front so starter templates (and ones you add) work
    // without tracking down "filter/function not found" errors.
    rustango_cms::markdown::register_tera_filter(&mut tera);
    rustango_cms::richtext::register_tera_filter(&mut tera);
    rustango_cms::translation::register_tera_filter(&mut tera);
    rustango_cms::block::tera_helpers::register_tera_function(&mut tera);
    rustango_cms::auto_menu::register_tera_function(&mut tera);
    rustango_cms::children_filtered::register_tera_function(&mut tera);
    rustango_cms::page_url::register_tera_function(&mut tera);
    rustango_cms::snippet_render::register_tera_function(&mut tera);
    rustango_cms::rendition::register_tera_function(&mut tera);
    rustango_cms::date_filters::register_tera_filters(&mut tera);
    let tera = Arc::new(tera);

    let migrations_dir = site_dir().join("migrations");
    // Backfill any CMS migrations newer than the ones written at generation
    // time, so this app always has the current schema regardless of when it
    // was scaffolded. Skips files that already exist; safe to run every boot.
    rustango_cms::migrations::materialize(&migrations_dir)?;

    // Media storage from the environment: local disk by default, or S3 with
    // `RCMS_MEDIA_BACKEND=s3` (build with rustango-cms's `storage_s3`).
    rustango_cms::media_storage::install_from_env()?;

    // Admin routing has two halves that must BOTH be mounted:
    //   • `public_router` — pre-auth routes: the branded `/login`, password
    //     reset, and the admin static assets (cms.css + JS). Without it the
    //     admin CSS/JS 404 (the public renderer's fallback claims them) and
    //     the admin renders unstyled.
    //   • `with_login_required(router(…))` — the login-gated `/cms-admin/*`
    //     CRUD (anonymous visitors 302 to `/login?next=…`).
    // Then merge the public CMS renderer, which claims the site root.
    let cms_admin = rustango_cms::admin::public_router(tera.clone()).merge(
        rustango_cms::admin::with_login_required(
            rustango_cms::admin::router(tera.clone()),
            "/login",
        ),
    );
    let api = cms_admin.merge(rustango_cms::router(tera));

    // The bundled admin forms emit `{{ csrf_token | csrf_input | safe }}`;
    // wire the matching CSRF middleware so tokens are validated on submit.
    // Outside production the cookie drops its `Secure` attribute, so the
    // admin works over plain http://localhost.
    //
    // `exempt_prefix` is required, not optional: the analytics beacon that
    // every public page injects POSTs to `/__cms__/collect` via
    // `navigator.sendBeacon`, which can't attach an `X-CSRF-Token` — and a
    // CDN-cached page may never have received a CSRF cookie at all. Without
    // the exemption every beacon 403s and the analytics dashboard stays empty
    // with no visible error.
    let mut csrf_cfg = rustango::forms::csrf::CsrfConfig::default()
        .exempt_prefix(rustango_cms::analytics::COLLECT_PATH);
    if !is_production() {
        csrf_cfg = csrf_cfg.allow_insecure_for_dev();
    }

    rustango::manage::Cli::new()
        .tenancy()
        .api(api)
        .migrations_dir(migrations_dir)
        .with_csrf_config(csrf_cfg)
        .seed(|registry| {
            let pool = registry.clone();
            async move {
                rustango_cms::ensure_seeded(&pool).await?;
                // Publish scheduled pages and take expired ones down on
                // time. Pass your page-cache invalidator here if you add one.
                rustango_cms::spawn_schedule_sweeper(
                    &pool,
                    std::time::Duration::from_secs(60),
                    rustango_cms::cache_invalidate::noop(),
                );
                Ok(())
            }
        })
        .run()
        .await
}
