//! Generate the embedded CMS baseline-migration list from the repo's
//! `migrations/` directory.
//!
//! This used to be a hand-written `const MIGRATIONS` in `src/main.rs` naming
//! five files by hand. When the migration set was squashed (0002..0005 folded
//! into `0001_cms_initial`), every `include_str!` target vanished and the
//! scaffolder stopped compiling — `rcms new` was dead for anyone who tried it
//! (#613). A hand-maintained list of filenames that must match a directory is
//! a rot machine, so we read the directory instead: add, remove or squash a
//! migration and the scaffolder simply follows.

use std::path::PathBuf;

fn main() {
    // crates/rcms-scaffold -> repo root
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("crate lives at <root>/crates/rcms-scaffold")
        .to_path_buf();
    let migrations = root.join("migrations");

    // Re-run when a migration is added, removed or edited.
    println!("cargo:rerun-if-changed={}", migrations.display());

    let mut entries: Vec<PathBuf> = std::fs::read_dir(&migrations)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", migrations.display()))
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "json"))
        .collect();
    // Apply order is the migration-name order, so sort by file name.
    entries.sort();

    assert!(
        !entries.is_empty(),
        "no migrations found in {} — the generated project would have no schema",
        migrations.display()
    );

    let mut out = String::from(
        "// @generated by build.rs from the repo's migrations/ directory.\n\
         const MIGRATIONS: &[(&str, &str)] = &[\n",
    );
    for path in &entries {
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("migration file name is valid UTF-8");
        println!("cargo:rerun-if-changed={}", path.display());
        out.push_str(&format!(
            "    ({stem:?}, include_str!({:?})),\n",
            path.display().to_string()
        ));
    }
    out.push_str("];\n");

    // The framework requirement the generated project must use. Read it from
    // the workspace manifest rather than hardcoding it in the template: the
    // template said `rustango = "0.44"` while the workspace had moved to 0.52,
    // so `[patch.crates-io]` no longer matched and a generated project pulled
    // BOTH the patched 0.52 (via rustango-cms) and registry 0.44 (its own
    // dep) — two copies of the framework in one graph (#613).
    let root_manifest = root.join("Cargo.toml");
    println!("cargo:rerun-if-changed={}", root_manifest.display());
    let manifest = std::fs::read_to_string(&root_manifest)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", root_manifest.display()));
    let req = manifest
        .lines()
        .find_map(|l| {
            let l = l.trim_start();
            let rest = l.strip_prefix("rustango = { version = \"")?;
            rest.split('"').next().map(str::to_owned)
        })
        .expect("workspace Cargo.toml declares `rustango = { version = \"…\"`");
    out.push_str(&format!(
        "// The framework requirement, read from the workspace manifest.\n\
         const RUSTANGO_REQ: &str = {req:?};\n"
    ));

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"))
        .join("migrations.rs");
    std::fs::write(&dest, out).expect("write generated migration list");
}
